//
//  UIColor+Extensions.swift
//  Palette
//
//  Created by Kevin Launay on 20/10/2025.
//  Generated by AI Claude Sonnet 4.7

import UIKit

extension UIColor {
    
    /// Calculates the relative luminance of the color
    /// Based on WCAG 2.0 specification
    var relativeLuminance: CGFloat {
        var red: CGFloat = 0
        var green: CGFloat = 0
        var blue: CGFloat = 0
        var alpha: CGFloat = 0
        
        getRed(&red, green: &green, blue: &blue, alpha: &alpha)
        
        // Apply the sRGB gamma correction
        func adjustComponent(_ component: CGFloat) -> CGFloat {
            if component <= 0.03928 {
                return component / 12.92
            } else {
                return pow((component + 0.055) / 1.055, 2.4)
            }
        }
        
        let r = adjustComponent(red)
        let g = adjustComponent(green)
        let b = adjustComponent(blue)
        
        // Calculate relative luminance
        return 0.2126 * r + 0.7152 * g + 0.0722 * b
    }
    
    /// Calculates the WCAG contrast ratio between this color and another color
    /// Returns a value between 1 (no contrast) and 21 (maximum contrast)
    /// - Parameter color: The color to compare against
    /// - Returns: The contrast ratio (1.0 to 21.0)
    func contrastRatio(with color: UIColor) -> CGFloat {
        let luminance1 = self.relativeLuminance
        let luminance2 = color.relativeLuminance
        
        let lighter = max(luminance1, luminance2)
        let darker = min(luminance1, luminance2)
        
        return (lighter + 0.05) / (darker + 0.05)
    }
    
    /// Checks if the contrast ratio meets WCAG AA standard (4.5:1 for normal text)
    /// - Parameter color: The color to compare against
    /// - Returns: True if the contrast meets WCAG AA standard
    func meetsWCAG_AA(with color: UIColor) -> Bool {
        return contrastRatio(with: color) >= 4.5
    }
    
    /// Checks if the contrast ratio meets WCAG AAA standard (7:1 for normal text)
    /// - Parameter color: The color to compare against
    /// - Returns: True if the contrast meets WCAG AAA standard
    func meetsWCAG_AAA(with color: UIColor) -> Bool {
        return contrastRatio(with: color) >= 7.0
    }
    
    /// Determines if the color is considered bright
    /// A color is bright if its relative luminance is greater than 0.5
    /// - Returns: True if the color is bright
    var isBright: Bool {
        return relativeLuminance > 0.5
    }
    
    /// Determines if the color is considered dark
    /// A color is dark if its relative luminance is less than or equal to 0.5
    /// - Returns: True if the color is dark
    var isDark: Bool {
        return relativeLuminance <= 0.5
    }
    
    /// Calculates the perceptual color difference using the CIE76 formula
    /// Returns the Euclidean distance in LAB color space
    /// - Parameter color: The color to compare against
    /// - Returns: The color difference (0 means identical, higher values mean more different)
    func colorDifference(with color: UIColor) -> CGFloat {
        // Convert to LAB color space for perceptual difference
        let lab1 = self.toLAB()
        let lab2 = color.toLAB()
        
        let deltaL = lab1.L - lab2.L
        let deltaA = lab1.a - lab2.a
        let deltaB = lab1.b - lab2.b
        
        return sqrt(deltaL * deltaL + deltaA * deltaA + deltaB * deltaB)
    }
    
    /// Convert RGB to LAB color space
    private func toLAB() -> (L: CGFloat, a: CGFloat, b: CGFloat) {
        var red: CGFloat = 0
        var green: CGFloat = 0
        var blue: CGFloat = 0
        var alpha: CGFloat = 0
        
        getRed(&red, green: &green, blue: &blue, alpha: &alpha)
        
        // Convert RGB to XYZ
        func pivotRGB(_ n: CGFloat) -> CGFloat {
            return n > 0.04045 ? pow((n + 0.055) / 1.055, 2.4) : n / 12.92
        }
        
        let r = pivotRGB(red) * 100
        let g = pivotRGB(green) * 100
        let b = pivotRGB(blue) * 100
        
        // Using D65 illuminant
        var x = r * 0.4124 + g * 0.3576 + b * 0.1805
        var y = r * 0.2126 + g * 0.7152 + b * 0.0722
        var z = r * 0.0193 + g * 0.1192 + b * 0.9505
        
        // Normalize for D65 white point
        x = x / 95.047
        y = y / 100.000
        z = z / 108.883
        
        // Convert XYZ to LAB
        func pivotXYZ(_ n: CGFloat) -> CGFloat {
            return n > 0.008856 ? pow(n, 1.0/3.0) : (7.787 * n) + (16.0 / 116.0)
        }
        
        x = pivotXYZ(x)
        y = pivotXYZ(y)
        z = pivotXYZ(z)
        
        let L = max(0, 116 * y - 16)
        let a = 500 * (x - y)
        let bVal = 200 * (y - z)
        
        return (L, a, bVal)
    }
}

// MARK: - Usage Examples
/*
 
 // Example 1: Calculate contrast ratio
 let textColor = UIColor.black
 let backgroundColor = UIColor.white
 let contrast = textColor.contrastRatio(with: backgroundColor)
 print("Contrast ratio: \(contrast)") // Output: ~21.0 (maximum contrast)
 
 // Example 2: Check WCAG compliance
 let darkGray = UIColor(white: 0.3, alpha: 1.0)
 let lightGray = UIColor(white: 0.9, alpha: 1.0)
 let meetsAA = darkGray.meetsWCAG_AA(with: lightGray)
 print("Meets WCAG AA: \(meetsAA)")
 
 // Example 3: Calculate perceptual color difference
 let red = UIColor.red
 let blue = UIColor.blue
 let difference = red.colorDifference(with: blue)
 print("Color difference: \(difference)")
 
 // Example 4: Find best text color for a background
 let bgColor = UIColor(red: 0.2, green: 0.5, blue: 0.8, alpha: 1.0)
 let whiteContrast = UIColor.white.contrastRatio(with: bgColor)
 let blackContrast = UIColor.black.contrastRatio(with: bgColor)
 let bestTextColor = whiteContrast > blackContrast ? UIColor.white : UIColor.black
 print("Best text color: \(bestTextColor == .white ? "White" : "Black")")
 
 // Example 5: Check if colors are bright or dark
 let yellow = UIColor.yellow
 let navy = UIColor(red: 0.0, green: 0.0, blue: 0.5, alpha: 1.0)
 print("Yellow is bright: \(yellow.isBright)") // true
 print("Navy is dark: \(navy.isDark)") // true
 
 // Example 6: Automatically choose text color based on background
 let background = UIColor(red: 0.8, green: 0.2, blue: 0.3, alpha: 1.0)
 let autoTextColor = background.isBright ? UIColor.black : UIColor.white
 print("Use \(autoTextColor == .white ? "white" : "black") text on this background")
 
 */
